name: {{cookiecutter.project_name}}
main: {{cookiecutter.main_package}}.{{cookiecutter.main_class}}
version: ${project.version}
description: {{cookiecutter.project_description}}
author: {{cookiecutter.project_author}}
depend: [{{cookiecutter.plugin_dependencies}}]
softdepend: []
